### ISSUE TITLE
topological_sort: Please either provide full cycle or document how to obtain it

### ISSUE THREAD

**Issue by joshtriplett** [samueltardieu/pathfinding#100]
The documentation for `pathfinding::topological_sort` states that if a cycle exists, it'll return one of the nodes in the cycle. Any number of algorithms could easily obtain the full cycle, or for that matter *all* cycles. If it would be trivial to do so, please consider providing the full cycle in the error. If not, please consider documenting, in the same function documentation, a simple, efficient way to find that cycle (or all cycles).

**Comment by samueltardieu** [comment]
This could benefit from having Johnson algorithm (#105) to find all cycles in a directed graph.
