### ISSUE TITLE
What about adding IDDFS? (I can do it)

### ISSUE THREAD

**Issue by felix91gr** [samueltardieu/pathfinding#132]
I think it's a good algorithm to have. It has the following properties:

- It's complete (like **BFS**)
- Its memory footprint is small (like **DFS**)

I'll talk about its time complexity at the end because it's not as important as these properties.

**IDDFS** may be the best of the "basic", non-heuristic, non-weighted algorithms. I like it a lot because it uses the same concepts behind **IDA***, which is my favorite heuristic search algorithm :heart: 

---

As promised, here is the time complexity:
- If _O(f(n))_ is the time complexity of **BFS**, the time complexity of **IDDFS** will be _O(k * f(n)) = O(f(n))_ for some constant k. That makes it suitable as an alternative to **BFS**.
- If **IDDFS** and **IDA*** are implemented without using heap allocation, they tend to be faster than **BFS** and **A***. If the `neighbors` function can be given as an iterator, then this certainly should be the case :sparkles:

**Comment by samueltardieu** [comment]
Looks like fun. Please be my guest.

**Comment by felix91gr** [comment]
I'll get to it then :grin:

**Comment by felix91gr** [comment]
Ah! I forgot to say... that IDDFS is optimal, as well! That's why it can be used as a replacement for BFS. I forgot that DFS isn't optimal, and I thought it was implicit that IDDFS was optimal as well :P 

Anyway, yeah. Now I think I've said all that I wanted to say :3

**Comment by felix91gr** [comment]
WIP PR is at #133 ^^
