### ISSUE TITLE
[Brainstorm?] More kinds of problems for benchmarks

### ISSUE THREAD

**Issue by felix91gr** [samueltardieu/pathfinding#139]
Currently the benchmarks only do search on a grid. But the structure of a grid isn't representative of all the kinds of problems for Search, far from it. The idea would be to have at least 2 more kinds of problems, with a different state-space structure.

**Comment by felix91gr** [comment]
### Problem 2 (after grid): Pancake Problem

[This paper](http://www2.informatik.uni-freiburg.de/~ki/papers/helmert-socs2010.pdf) explains it well. It's a very interesting problem, which I've studied before. I can provide an implementation for it no problem.

**Comment by sinistersnare** [comment]
I have only just seen this library (am planning on using it for a game), and I wonder if the [knights tour](https://en.wikipedia.org/wiki/Knight%27s_tour) can be modeled using this library? It may be a good benchmark problem

**Comment by felix91gr** [comment]
It can be, yes. But I don't think it's a good benchmark, since the length of the "optimal path" is constant. That's why the Knight's Tour is usually modeled as a CSP (constraint satisfaction problem) and solved accordingly (using backtracking with heuristics, for example 🙂). All Search algorithms lose their strength as soon as the solution depth becomes constant.

That said, if at some point there are algorithms for solving CSP problems in this crate, it would be a great benchmark for those! :)
