### ISSUE TITLE
Cost of movements

### ISSUE THREAD

**Issue by Martin1887** [samueltardieu/pathfinding#145]
If I have understood well the documentation, all algorithms suppose a constant cost of all movements. Thus, the best path is the path with less movements.

However, the most of algorithms (probably all, but I do not know all) support costs. For instance, the heuristic defined by A* and IDA* is `f = g + h` where `g` is the cost and `h` is the user defined heuristic. Dijkstra's evaluation function is `f = g` as well, considering only the cost.

I think that supporting costs would do the library very more useful.

**Comment by samueltardieu** [comment]
I am not sure I follow. Of course you can indicate costs in Dijkstra and other algorithms, as is shown in the documentation and in `tests/pathfinding.rs` for example.

Or I have misunderstood what you said?

**Comment by Martin1887** [comment]
Sorry, I had not seen that weights can be specified in a tuple in each neighbor. The issue can be closed then.
