### ISSUE TITLE
A more consistent API using traits

### ISSUE THREAD

**Issue by Martin1887** [samueltardieu/pathfinding#146]
The most of algorithms have a very similar signature, since the objective or all are finding the best path.

Therefore, this seems to be a perfect case to use traits, making the API more consistent and functions more clean with less generic arguments. The inconveniences are that this would be a breaking change and that closures wouldn't be used directly without a struct (although putting some closures as parameters of a function is a bit cumbersome, so this inconvenience is not so important).

For instance, a trait `Graph` could have a type `N`, a type `C`, a `neighbors` function to get neighbors, a `heuristic` function to return the heuristic (with default implementation returning 0 for the cases when a heuristic algorithm is not wanted) and a `cost` function returning the cost between two neighbors (with default implementation returning 1 for the unweighted graphs). This would also solve #145.

Of course, this is only a preliminary suggestion.

**Comment by dlight** [comment]
Maybe also offer an optional feature for integration with `petgraph` traits?
