### ISSUE TITLE
topological_sort_into_groups

### ISSUE THREAD

**Issue by mdsteele** [samueltardieu/pathfinding#174]
For an application I'm working on, I'd be interested in adding a new `topological_sort_into_groups` function to `pathfinding::directed::topological_sort` that, rather than just producing a single ordering of nodes, would partition the nodes into groups -- the first group would have all nodes with no dependencies, the second group would have all nodes whose only dependencies are in the first group, and so on.  Concatenating the groups would then produce a valid topological sort regardless of how the nodes in each group were reordered.

This should be doable in O(V+E) time with a pretty straightforward variation on [Kahn's algorithm](https://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm).  (Maybe this specific variation already has a name?  If so, I'm not sure what it is.)

I'd be happy to put together a PR for this if it would be welcome.

**Comment by samueltardieu** [comment]
This would be great indeed!
