### ISSUE TITLE
bfs_loop perfomance problem

### ISSUE THREAD

**Issue by MikailBag** [samueltardieu/pathfinding#207]
Hi!
bfs_loop() function is O(N**2), unfortunately.
Consider such an example:
Graph containts 2*N+1 node, from 0 to 2*N.
Edges:
- From 0 to each node in segment [1, N] - N edges
- From each node in segment [1, N] - to N+1 - N edges
- From each node in segment [N+1, 2N-1] - to next node - N-1 edge
- There is no edges from last, 2Nth node.
Here is visualisation of graph with N=5
![image](https://user-images.githubusercontent.com/11889433/51624949-0ea2bd80-1f4d-11e9-9040-2505e148e71d.png)
How bfs_loop(0, ...) processes this graph:
It can't find edge from 0 to 0, so it starts iterating over 0 siblings
For each sibling bfs is launched, which traverses O(N) nodes.
Bfs is launched O(N) times - from each node in [1, N].
O(N*N) in total.

**Comment by MikailBag** [comment]
I also have written some benchmarks:
https://gist.github.com/MikailBag/fd18f36a79b53b9b564d74617af34fb0
While input size proportion is 1:10:20, time spent proportion is 1:100:400, which is another proof for bfs_loop perfomance problems

**Comment by samueltardieu** [comment]
Indeed. I am testing a fix, which in addition factors out more code and reduces the complexity. Thanks for the detailed report.

Once the fix is on master, I will also put it on the 1.x branch and make a new release.
