### ISSUE TITLE
how to set timeout for algoritms?

### ISSUE THREAD

**Issue by piaoger** [samueltardieu/pathfinding#210]
In some cases,complex or large scenes,the search time can be large，do me have a way to break the loop? or we need to add a new timelimit argument for algorithms?

**Comment by samueltardieu** [comment]
It depends on the algorithm. I have not add the need for this, but I could envision several ways of achieving this:

- have your `neighbours` function return an empty iterator after the timeout has elapsed: in this case, the exploration will continue with only the nodes that have been seen so far and return suboptimal (read "wrong") resutls;
- have your `success` function check if the timeout has elapsed, in which case it would set an external flag signalling the failure and will return `true`: you'll get a result but the external flag will tell you that it is a dummy one.

It would be useful to include such an example in the documentation as it might be useful in many cases.

**Comment by piaoger** [comment]
thanks @samueltardieu , I chosen to tweak success check for my requirement ：）
