### ISSUE TITLE
less heap allocation in star

### ISSUE THREAD

**Issue by extrawurst** [samueltardieu/pathfinding#234]
I was wondering if there is a way cache the `BinaryHeap` and `IndexMap` that `astar` uses internally to reduce heap allocations? Is there a way to have a method of astar that allows us to pass those in as a param?

**Comment by samueltardieu** [comment]
Are you sure that would change the performances in a significant way? Have you measured it?

**Comment by Extrawurst** [comment]
I did not benchmark it, but heap allocations are more expensive than no heap allocations AFAIK. Let me followup with a benchmark as soon as I can get to it.
