### ISSUE TITLE
Ability to return edges instead of/addition to nodes

### ISSUE THREAD

**Issue by Recmo** [samueltardieu/pathfinding#235]
I'm using the A* implementation to find the shortest path in a complicated directed graph, which works great! 

The problem is, my graph often has multiple edges of different weight going between two nodes and I need to know which ones is taken. I can manually search between each pair of nodes, but this feels cumbersome. I could also replace the node type with `(Edge, Node)` to keep track of the edges taken, but this breaks the `Eq` and `Hash` traits`.

**Comment by samueltardieu** [comment]
The resulting path will always use the lowest weight edge between two nodes, won't it? Why don't you simplify the graph to collapse all edges between two nodes into the lowest weight one?
If your problem implies a dynamic state, then the selected edges can be stored there, can't they?
