### ISSUE TITLE
Can't use dijkstra with float costs

### ISSUE THREAD

**Issue by dylemma** [samueltardieu/pathfinding#242]
dijkstra(
    ^^^^^^^^ the trait `std::cmp::Ord` is not implemented for `{float}`

    C: Zero + Ord + Copy,
              --- required by this bound in `pathfinding::directed::dijkstra::dijkstra`

Since `f32` is `PartialOrd` but not `Ord`, I can't use the `dijkstra` function with e.g. `f32` as the Cost type.
My workaround for now has been to multiply by some constant factor like 1000 and cast to i32, but I think the algorithm should still work if the constraint on `C` was reduced to `PartialOrd` instead of `Ord`. Maybe `PartialOrd + PartialEq`?

**Comment by samueltardieu** [comment]
`f32` would let you use `f32::NAN` which would make no sense in the algorithm. You can use float wrappers such as the one available in the [ordered-float](https://crates.io/crates/ordered-float) crate to overcome this possibility.

I'll mention this in the documentation for reference.

**Comment by dylemma** [comment]
I finally got back to this and have discovered a new wrinkle. 

> the trait `num_traits::identities::Zero` is not implemented for `ordered_float::OrderedFloat<f64>`

Since both are third-party to my program, my understanding is that I can't just implement a `Zero` for `OrderedFloat<f64>` For my own learning's sake, is my only choice to make my own wrapper for `f64` and implement each of the required traits? (Besides trying to make a PR to the ordered-float repo). Is there some other way to accomplish this?

**Comment by samueltardieu** [comment]
You can (as you wrote in your initial report) use a fixed-point type by using a multiplier. Are your costs really floats, which means that they can range from approximately 2⋅10⁻³⁴ to 10³⁸ ? Did you acquire them from a formula which can held irrational numbers, or do they use a fixed precision to start with?

Floating point types should not be used indiscriminately and are often the wrong choice to begin with in path finding algorithms, unless you are trying to build a path through the entire solar system with edges having a length of a few atoms.

**Comment by dylemma** [comment]
Hmm that is a fair point. My use case is in game geometry (working towards an implementation of http://jceipek.com/Olin-Coding-Tutorials/pathing.html). NCollide is part of the mix, so I ended up with `f64` as the scalar type for Points. But I suppose I don't need all of that precision, so I'll go back to the "using a multiplier" approach. Thank you for the advice and perspective.
