### ISSUE TITLE
'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by laticoda** [samueltardieu/pathfinding#251]
hello, i got this:
**thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `7`,
 right: `5`', src/main.rs:22:1**

with this:
```
use pathfinding::prelude::bfs;

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct Pos(i32, i32);

impl Pos {
  fn successors(&self) -> Vec<Pos> {
    let &Pos(x, y) = self;
    vec![Pos(x+1,y+2), Pos(x+1,y-2), Pos(x-1,y+2), Pos(x-1,y-2),
         Pos(x+2,y+1), Pos(x+2,y-1), Pos(x-2,y+1), Pos(x-2,y-1)]
  }
}

fn main() {


static GOAL: Pos = Pos(**8, 8**);

let result = bfs(&Pos(1, 1), |p| p.successors(), |p| *p == GOAL);

//println!("{:?}",result);
assert_eq!(result.expect("no path found").len(), 5);
}
```

**Comment by laticoda** [comment]
i wanted to bold inside the code , not good idea, so:
`static GOAL: Pos = Pos(8, 8);`

**Comment by samueltardieu** [comment]
@laticoda What path did you expect it to find? Isn't `[Pos(1, 1), Pos(2, 3), Pos(3, 5), Pos(4, 7), Pos(5, 9), Pos(6, 7), Pos(8, 8)]` the shortest one?

**Comment by samueltardieu** [comment]
If you model a knight on a chess board and add the right filter

```rust
    fn successors(&self) -> Vec<Pos> {
        let &Pos(x, y) = self;
        vec![
            Pos(x + 1, y + 2),
            Pos(x + 1, y - 2),
            Pos(x - 1, y + 2),
            Pos(x - 1, y - 2),
            Pos(x + 2, y + 1),
            Pos(x + 2, y - 1),
            Pos(x - 2, y + 1),
            Pos(x - 2, y - 1),
        ]
        .into_iter()
        .filter(|&Pos(x, y)| x > 0 && x <= 8 && y > 0 && y <= 8)
        .collect()
    }
```

then the solution is in 7 steps (6 moves + starting point): `[Pos(1, 1), Pos(2, 3), Pos(3, 5), Pos(4, 7), Pos(5, 5), Pos(6, 7), Pos(8, 8)]`. This is consistent with https://www.techiedelight.com/chess-knight-problem-find-shortest-path-source-destination/.

**Comment by laticoda** [comment]
Hello, pathfinding is great but i use it another way to find path on a board game greater than 8x8
 (for example 80x80) and i have to introduce some walls . I'm thinking about how to succeed this little hack.

**Comment by samueltardieu** [comment]
@laticoda Regarding this issue, do you think there is a bug or not?

**Comment by BinAlyan** [comment]
@laticoda 
Yes you can do mazes, you need to implement the successors function to return only legal positions according to your **rules**.

You need to put boundaries checks and the wall check in the successors function. Do not return a position if for example, its y or x position is greater than 80. For walls, you could for example have a map of blocked positions and if positions is part of blocked positions, do not return it.


Although I don't think this relevant to this issue, which I do not think as a bug.

**Comment by samueltardieu** [comment]
I'm closing the issue, please reopen if this is indeed a bug which I don't think this is.
