### ISSUE TITLE
Possible to quickly compute "all nodes within a distance of D" from an initial node?

### ISSUE THREAD

**Issue by paulkernfeld** [samueltardieu/pathfinding#268]
Given an undirected graph _G_ (obviously fine to think of this as directed), I'd like to have a quick way to answer the question: given a starting node _N_ and a distance _D_, what are all the nodes that are less than or equal to _D_ from node _N_?

Context: I'm working on a tiny city sim game on a grid. The rule is that the building you may build on node _N_ is constrained by the pre-existing buildings that are "connected" to node _N_, i.e. the buildings that are within distance _D_ of node _N_. I'm currently pre-computing a set of the nodes that are connected to any given node, but my algorithm is so slow that it takes seconds on even a 6x6 graph 😞! The reason that this isn't just "check the Manhattan distance" is because there are some buildings that you can travel between for zero cost.

**Comment by samueltardieu** [comment]
To precompute the distances between each pair of vertices in your graph, you might want to either Floyd-Warshall or repeated Dijkstra, depending on the number of vertices and edges.

**Comment by samueltardieu** [comment]
And to answer your initial question (find all nodes within a given distance of another node) you might want to use a modified Dijkstra algorithm, look at `run_dijkstra` for example in `dijkstra.rs`.

**Comment by paulkernfeld** [comment]
Thanks! I had never heard of Floyd-Warshall and it looks super-relevant! I just realized that I'll probably have to implement a custom algorithm because my `C` type only implements `PartialOrd`, not `Ord`. I suspect that this is too weird a use case to justify adding to this library. 🤪
