### ISSUE TITLE
A "which function" guide for beginners?

### ISSUE THREAD

**Issue by paulkernfeld** [samueltardieu/pathfinding#269]
The selection of algorithms here is amazing! 😍 As an effect of that, it's taking me a while to figure out which function I want, even though I've heard of most of the algorithms before. For beginners (or lazy people like me 😁), what do you think of adding a "which function should I choose" section to the README? I'd be happy to try writing this. The goal wouldn't be to solve every problem, but rather to provide reasonable guidance on where to start.

**Comment by samueltardieu** [comment]
Please be my guest.
