### ISSUE TITLE
Slight optimizations

### ISSUE THREAD

**Issue by tko** [samueltardieu/pathfinding#3]
The `astar` and `bfs` implementations seem to use a pattern `if !hash.contains(key) { hash.insert(key); }` which is essentially two separate lookups into the hash table. The `entry` API would allow to avoid one with slightly better performance, e.g. for astar

```rust
match parents.entry(neighbour.clone()) {
    Vacant(ent) => {
        ent.insert((node.clone(), new_cost));
        to_see.push(..);
    },
    Occupied(ent) => if new_cost < ent.get().1 {
        ent.into_mut().1 = new_cost;
        to_see.push(..);
    },
}
```

Using `BTreeMap` instead of `HashMap` could be better in some cases provided that nodes that are visited after each other are also sorted close to each other; in theory BTreeMap would be more cache friendly in such case. That may not be generally applicable though, and the `Ord` vs. `Eq + Hash` requirement might be too strict.

**Comment by samueltardieu** [comment]
Concerning `BTreeMap`, there is no reason that nodes are visited in a sequence related to some ordering.

As far as `Entry` is concerned, I thought about it, but cloning the neighbour might be an heavy operation compared to rehashing its value, so for my use cases at least I would get degraded performances (the nodes are a complex state with lots of information).

**Comment by tko** [comment]
The `parents` map is accessed in a sequence of neighbours of a given node; if the `Ord` of neighbours are "similar" then most/all the neighbours could be stored in the same bucket and avoid many cache misses. Much depends on the variables though and might be unworkable with many dimensions. (As I understand applying [Z-order curve](https://en.wikipedia.org/wiki/Z-order_curve) could further improve cache locality but haven't tried.)

Good point about cloning, but it doesn't seem to hold in a silly benchmark. From what I can tell `entry` is little faster and `BTreeMap` is consistently little better than `HashMap`.

```
test no_path_bfs_btree            ... bench:  23,309,042 ns/iter (+/- 1,987,065)
test no_path_bfs_btree_entry      ... bench:  21,184,136 ns/iter (+/- 2,844,694)
test no_path_bfs_hash             ... bench:  43,221,915 ns/iter (+/- 2,930,601)
test no_path_bfs_hash_entry       ... bench:  40,675,633 ns/iter (+/- 3,201,112)
test no_path_dijkstra_btree       ... bench:  31,611,012 ns/iter (+/- 3,400,351)
test no_path_dijkstra_btree_entry ... bench:  29,645,208 ns/iter (+/- 2,190,278)
test no_path_dijkstra_hash        ... bench:  53,518,070 ns/iter (+/- 3,224,821)
test no_path_dijkstra_hash_entry  ... bench:  49,549,401 ns/iter (+/- 3,367,472)
```

The test is just visiting every node in 128x128 grid moving up/down/left/right with some padding in the state to stress the effects cloning. Maybe it's too trivial?
```rust
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct Pt{x: u16, y: u16, _fill: [u64; 32]}
impl Pt {
    fn new(x: u16, y: u16) -> Pt {
        Pt{x: x, y: y, _fill: [0u64; 32]}
    }
}

#[inline]
fn neighbours(pt: &Pt) -> Vec<Pt> {
    let mut ret = vec![];
    if    0 < pt.x { ret.push(Pt::new(pt.x - 1, pt.y))}
    if pt.x < 128  { ret.push(Pt::new(pt.x + 1, pt.y))}
    if    0 < pt.y { ret.push(Pt::new(pt.x, pt.y - 1))}
    if pt.y < 128  { ret.push(Pt::new(pt.x, pt.y + 1))}
    ret
}

#[bench]
fn no_path_bfs_hash(b: &mut Bencher) {
    b.iter(|| assert_eq!(bfs_hash(&Pt::new(2, 3),
                                  |n| neighbours(n),
                                  |_| false),
                         None));
}
```

**Comment by samueltardieu** [comment]
Interesting benchmark about cloning. I'll reexamine the suggestion with my dataset, you might well have a point.

**Comment by tko** [comment]
On related note, I just tested this with a z-coordinate instead of the filler. While `entry` is still slightly faster with both maps, now hash beats btree. I guess it makes sense, _all_ variables are always hashed so their total number/size/hash complexity matters, but ordering can break out on the first difference. There is a threshold there somewhere.

Then again a cheaper hash could probably make hash always faster.
