### ISSUE TITLE
Munkres: debug_assert can falsely activate for small floats

### ISSUE THREAD

**Issue by nemosupremo** [samueltardieu/pathfinding#332]
https://github.com/samueltardieu/pathfinding/blob/55f99f3d1c1e892595369594a482fc173191557a/src/kuhn_munkres.rs#L148

This can crash a program (running in debug mode) if the two values are pretty small. I considered swapping the assert for an f32::EPSILON, but that obviously wouldn't work when C is a `usize` or something. I think the best option would be to remove the assertion?

**Comment by samueltardieu** [comment]
Those `debug_assert!()` should have been removed sooner anyway. Thanks for the report.
