### ISSUE TITLE
[Feature Request] Expand planner algorithm offering

### ISSUE THREAD

**Issue by HenriFrancais** [samueltardieu/pathfinding#340]
This project already has a good selection of planning algorithms, but some common categories that are currently not represented include:

Any Angle Planners (such as [Theta*](https://en.wikipedia.org/wiki/Theta*) and its derivatives)
Sample Based Planners (such as [RRT](https://en.wikipedia.org/wiki/Rapidly-exploring_random_tree) and its derivatives)

Is there appetite for expanding the project along this axis?

**Comment by samueltardieu** [comment]
Hi. Theta* would certainly be useful and usable out of the box. RRT however has so many derivatives and specialized extensions that I am not sure in which situation the generic algorithm could be used.
