### ISSUE TITLE
kuhn_munkres doesn't terminate for some inputs

### ISSUE THREAD

**Issue by rihardsk** [samueltardieu/pathfinding#349]
Here's how to reproduce:
```rust
use ordered_float::OrderedFloat;
use pathfinding::{prelude::{kuhn_munkres_min, Matrix}};

fn main() {
    // Using f32::NAN or f32::NEG_INFINITY has the same effect here
    let mat = Matrix::new(2, 2, OrderedFloat(f32::INFINITY));
    let res = kuhn_munkres_min(&mat);
    // This line is never reached
    dbg!(res);
}
```
`OrderedFloat` comes from the `ordered-float` crate.

**Comment by samueltardieu** [comment]
Indeed, the total cost should not exceed the maximum of the given type, and the intermediate computations (which never exceed the total cost) should not overflow or give an absorbing value such as `{NEG_,}INFINITY` or `NAN`. I will fix the documentation to include this, and we can think about a future non-API compatible signature that would let `kuhn_munkres()` and other functions detect ill-formed parameters.

**Comment by samueltardieu** [comment]
I'll close this and release a new version with a completed documentation. We can open another issue if an interface change is needed. Thanks for the report.
