### ISSUE TITLE
[Question/Feature request] Pathfinding on a hex grid

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [samueltardieu/pathfinding#391]
Is it possible to use this lib for pathfinding on a hexagonal grid? If not, it t would be awesome if support for this is added.

**Comment by samueltardieu** [comment]
Pathfinding algorithms in this library are not tied to any state representation. You can look at the `sliding-puzzle` example which is an example of a sliding puzzle (as the name indicates) and doesn't use any grid.

So yes, as long as you can figure out how to represent your various tiles and which tiles are neighbours of others, it will be perfectly suitable.
