### ISSUE TITLE
Hello! This library is very interesting! Have you considered integrating some of your code in retworkx? 

### ISSUE THREAD

**Issue by das-dias** [samueltardieu/pathfinding#429]
Its a rust library implementing an evolution of the networkx python graph manipulation library. You should check it out!

**Comment by das-dias** [comment]
Its a rust library implementing an evolution of the networkx python graph manipulation library. You should check it out!

**Comment by samueltardieu** [comment]
I haven't, but feel free to do it if you need it (preferably by depending on this package so that bugfixes are incorporated automatically).
