### ISSUE TITLE
Jump point search?

### ISSUE THREAD

**Issue by expenses** [samueltardieu/pathfinding#8]
Hi, I haven't really looked into the requirements of this, but do you think it would be possible to implement [jump point search]? [This explanation][explanation] might be a good starting point. I'd take a look at it, but I'm a little busy right now.

[jump point search]: https://en.wikipedia.org/wiki/Jump_point_search
[explanation]: https://zerowidth.com/2013/05/05/jump-point-search-explained.html

**Comment by samueltardieu** [comment]
There are no plans to integrate JPS at the moment, but contributions are always welcome.
